#!/bin/bash

echo "Updating repo data"
apt update
echo "Installing ruby packets"
apt install -y ruby-full ruby-bundler build-essential
echo "Installation Done! Current versions of ruby and bundler:"
ruby -v
bundler -v

echo "Adding mongodb repo"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'

echo "Updating repo data"
apt update
echo "Installing mongodb"
apt install -y mongodb-org
echo "Starting mongod"
systemctl enable mongod
systemctl start mongod

echo "Cloning reddit repo"
git clone -b monolith https://github.com/express42/reddit.git

echo "Install dependencies"
cd reddit && bundle install

echo "Starting puma"
puma -d

echo "Check puma"
ps aux | grep puma
