---
- name: Configure App host
  hosts: app
  tags: app-tag
  become: true
  vars:
      db_host: 10.132.15.215:27017
  tasks:
      - name: Add unit file for Puma
        copy:
            src: files/puma.service
            dest: /etc/systemd/system/puma.service
        notify: reload puma

      - name: Add config for DB connection
        template:
            src: templates/db_config.j2
            dest: /home/appuser/db_config
        notify: reload puma

      - name: enable puma
        become: true
        systemd: name=puma enabled=yes
  handlers:
      - name: reload puma
        systemd: name=puma state=restarted

