all:
    children:
        app:
            hosts:
                appserver:
                    ansible_host: 34.76.160.11 
        db:
            hosts:
                dbserver:
                    ansible_host: 35.205.45.2
