---
- name: Mongod Provisioning
  hosts: all
  become: true
  tasks:
        - name: Install mongod
          apt:
                update_cache: yes
                name: "{{ packages  }}"
          vars:
                packages:
                  -  mongodb-org

        - name: Start and enable mongod
          systemd:
                enabled: yes
                state: started
                name: mongod
